/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;

import java.awt.CardLayout;
import java.awt.Dimension;
import java.awt.Toolkit;

/**
 *
 * @author user
 */
public class PilihGambarButton extends javax.swing.JFrame {

    /**
     * Creates new form PilihGambarButton
     */
    public PilihGambarButton() {
        initComponents();
        
         Dimension screenSize = 
         Toolkit.getDefaultToolkit().getScreenSize();
            Dimension frameSize = this.getSize();
            if (frameSize.height > screenSize.height) {
                frameSize.height = screenSize.height;
            }
            if (frameSize.width > screenSize.width) {
                frameSize.width = screenSize.width;
            }
            this.setLocation(
                    (screenSize.width - frameSize.width) / 2, 
                    (screenSize.height - frameSize.height) / 2); 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        buttonPanel = new javax.swing.JPanel();
        btnIg = new javax.swing.JButton();
        btnCs2 = new javax.swing.JButton();
        btnTwitter = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();
        imagePanel = new javax.swing.JPanel();
        lblIg = new javax.swing.JLabel();
        lblWa = new javax.swing.JLabel();
        lblTwitter = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        buttonPanel.setBackground(new java.awt.Color(0, 0, 0));

        btnIg.setText("Instagram");
        btnIg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIgActionPerformed(evt);
            }
        });
        buttonPanel.add(btnIg);

        btnCs2.setText("Whatsapp");
        btnCs2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCs2ActionPerformed(evt);
            }
        });
        buttonPanel.add(btnCs2);

        btnTwitter.setText("Twitter");
        btnTwitter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTwitterActionPerformed(evt);
            }
        });
        buttonPanel.add(btnTwitter);

        btnExit.setText("Exit");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });
        buttonPanel.add(btnExit);

        getContentPane().add(buttonPanel, java.awt.BorderLayout.PAGE_START);

        imagePanel.setLayout(new java.awt.CardLayout());

        lblIg.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblIg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Instagram.jpg"))); // NOI18N
        imagePanel.add(lblIg, "1");

        lblWa.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblWa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Whatsapp.jpg"))); // NOI18N
        imagePanel.add(lblWa, "2");

        lblTwitter.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTwitter.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Twitter.jpg"))); // NOI18N
        imagePanel.add(lblTwitter, "3");

        getContentPane().add(imagePanel, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnIgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIgActionPerformed
        CardLayout cl = (CardLayout)(imagePanel.getLayout());
       cl.show(imagePanel, "1");
    }//GEN-LAST:event_btnIgActionPerformed

    private void btnCs2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCs2ActionPerformed
         CardLayout cl = (CardLayout)(imagePanel.getLayout());
        cl.show(imagePanel, "2");
    }//GEN-LAST:event_btnCs2ActionPerformed

    private void btnTwitterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTwitterActionPerformed
         CardLayout cl = (CardLayout)(imagePanel.getLayout());
        cl.show(imagePanel, "3");
    }//GEN-LAST:event_btnTwitterActionPerformed

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnExitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PilihGambarButton.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PilihGambarButton.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PilihGambarButton.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PilihGambarButton.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new PilihGambarButton().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCs2;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnIg;
    private javax.swing.JButton btnTwitter;
    private javax.swing.JPanel buttonPanel;
    private javax.swing.JPanel imagePanel;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblIg;
    private javax.swing.JLabel lblTwitter;
    private javax.swing.JLabel lblWa;
    // End of variables declaration//GEN-END:variables
}
